# Generated by Django 5.2.7 on 2025-10-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('detection_results', models.JSONField(default=dict)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('total_detections', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Detection Result',
                'verbose_name_plural': 'Detection Results',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
